name: package-publish

on: workflow_dispatch

jobs:
  package-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Package
        run: corepack enable && yarn install
      - name:
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run:  yarn version:publish
